# GENERATED BY KOMAND SDK - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Gets the managed IP list from this plugin"


class Input:
    pass

class Output:
    IP_LIST = "ip_list"
    

class GetIpListInput(insightconnect_plugin_runtime.Input):
    schema = json.loads("""
   {}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetIpListOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "ip_list": {
      "type": "array",
      "title": "IP List",
      "description": "List of IP and CIDR addresses stored in this plugin",
      "items": {
        "type": "string"
      },
      "order": 1
    }
  },
  "required": [
    "ip_list"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
