# GENERATED BY KOMAND SDK - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Check if a given IP is included in any of the IPs or CIDR addresses managed by this plugin"


class Input:
    IP_ADDRESS = "ip_address"
    

class Output:
    IS_IN_LIST = "is_in_list"
    

class CheckIfIpIsInListInput(insightconnect_plugin_runtime.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "ip_address": {
      "type": "string",
      "title": "IP Address",
      "description": "IP Address to check",
      "order": 1
    }
  },
  "required": [
    "ip_address"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class CheckIfIpIsInListOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "is_in_list": {
      "type": "boolean",
      "title": "Is in List",
      "description": "Is the IP in the list",
      "order": 1
    }
  },
  "required": [
    "is_in_list"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
